name: Publishing Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build package
        run: python setup.py bdist_wheel

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Deploy to PyPI
        run: twine upload dist/*

env:
  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
